# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ab7e80cdbfd1ceab0f76263b5caad59fe05914ccb0825178ba1ac89bc94a56cde3ca1fd20f9c58ea7421c500ee71aa65daa79a8ab249bf539f900e98aaf032b3

test:
  secret_key_base: ddf17f937823f8eb4f21fda76e94bdf2599349f9182f9e5d363d9124d8d795370f504e9e4731cb494a367227cecdbf0c7188a596806a7e5e1609bc5d73d619b3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
